name: Setup

description: Sets up the repository and its dependencies.

runs:
  using: composite
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17.0.17'

    - name: Set up Leiningen
      uses: DeLaGuardo/setup-clojure@ada62bb3282a01a296659d48378b812b8e097360 # 13.2
      with:
        lein: '2.12.0'

    - name: Cache Clojure dependencies
      uses: actions/cache@v4
      with:
        key: cljdeps-${{ hashFiles('project.clj') }}
        path: ~/.m2/repository
        restore-keys: cljdeps-
