version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-${BUILD_FLAVOR}
    image: nhl-score-api-${BUILD_FLAVOR}
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis
