name: Deployment to Heroku

on:
  workflow_dispatch:

permissions:
  checks: read
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure checks have passed
        run: |
          all_success=$(gh api \
            repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs \
            --jq 'all(.check_runs[]; .conclusion == "success")')

          echo "All checks successful: $all_success"

          if [ "$all_success" != "true" ]; then
            echo "Not all checks have passed, aborting deployment"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: checks
    uses: ./.github/workflows/build.yml
    # with:
    #   upload: true

  # upload-to-heroku:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment: nhl-score-api
  #   steps:
  #     - uses: actions/checkout@v6

  #     - name: Set up Heroku CLI
  #       run: curl https://cli-assets.heroku.com/install.sh | sh

  #     - name: Configure Heroku
  #       env:
  #         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #       run: heroku git:remote --app ${{ vars.HEROKU_APP_NAME }}

  #     - name: Download uberjar
  #       uses: actions/download-artifact@v6
  #       with:
  #         name: target-directory
  #         path: target

  #     - name: Deploy to Heroku
  #       env:
  #         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #       run: ./deploy.sh
